services:
  - type: web
    name: p2p-web-share
    runtime: node
    plan: free
    buildCommand: cd client && npm install --include=dev && npm run build && cd ../server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
