#pragma once
// ---------------------------------------------------------------------------
// Zero-knowledge encryption (AES-256-GCM) and integrity (SHA-256), via OpenSSL.
//
// The key is generated by the sender and only travels inside the share link's
// fragment (`#key=...`). Peers never send it to the signaling server.
// Ciphertext layout matches the Web Crypto API: [IV (12)][ciphertext][tag (16)].
// ---------------------------------------------------------------------------

#include <array>
#include <optional>
#include <string>
#include <string_view>

#include "core/base64.hpp"

namespace p2p {

constexpr size_t kKeySize = 32;
constexpr size_t kIvSize = 12;
constexpr size_t kTagSize = 16;

class Key {
 public:
  static Key generate();
  /** Parse the base64url text from a link. Throws std::invalid_argument. */
  static Key fromString(std::string_view text);
  std::string toString() const;
  const uint8_t* data() const { return bytes_.data(); }

 private:
  std::array<uint8_t, kKeySize> bytes_{};
};

/** Encrypt with a fresh random IV. `aad` is authenticated but not encrypted. */
Bytes encrypt(const Key& key, const uint8_t* data, size_t size, const uint8_t* aad, size_t aadSize);

/** Encrypt with a caller-chosen IV (for test vectors only; never reuse an IV). */
Bytes encryptWithIv(const Key& key, const uint8_t* iv, const uint8_t* data, size_t size,
                    const uint8_t* aad, size_t aadSize);

/** Returns nullopt if the key is wrong or the data or aad were tampered with. */
std::optional<Bytes> decrypt(const Key& key, const uint8_t* payload, size_t size, const uint8_t* aad,
                             size_t aadSize);

std::array<uint8_t, 32> sha256(const uint8_t* data, size_t size);
std::string sha256Hex(const uint8_t* data, size_t size);
inline std::string sha256Hex(std::string_view text) {
  return sha256Hex(reinterpret_cast<const uint8_t*>(text.data()), text.size());
}

void randomBytes(uint8_t* out, size_t size);
/** Random lowercase hex id, `bytes` bytes long (room ids, peer ids, nonces). */
std::string randomId(size_t bytes);

}  // namespace p2p
